let Users = [
  {
    id: 1,
    name: "Mr Tomiwa",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "12/05/1995",
    img: "https://picsum.photos/200/400",
    numberOfLockNow: 5,
    NumOfSchedule: 1,
    numOfLockByDailyLImit: 2,
    addictive: [
      { logo: "https://picsum.photos/200/420", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/430", appName: "youtube" },
      { logo: "https://picsum.photos/200/440", appName: "instagram" },
      { logo: "https://picsum.photos/200/450", appName: "twitter" },
      { logo: "https://picsum.photos/200/460", appName: "google chrome" },
      { logo: "https://picsum.photos/200/470", appName: "opera news" },
    ],
    accountabilityPartner: {
      name: "Musa",
      email: "example@gmail.com",
    },
  },
  {
    id: 2,
    name: "Mr Julius",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "10/31/2000",
    img: "https://source.unsplash.com/user/c_v_r",
    numberOfLockNow: 50,
    NumOfSchedule: 10,
    numOfLockByDailyLImit: 2,
    addictive: [
      { logo: "https://picsum.photos/200/480", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/490", appName: "youtube" },
      { logo: "https://picsum.photos/200/310", appName: "instagram" },
      { logo: "https://picsum.photos/200/320", appName: "twitter" },
    ],
    accountabilityPartner: {
      name: "judith",
      email: "example@gmail.com",
    },
  },
  {
    id: 3,
    name: "Mr Josh",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "07/22/2003",
    img: "https://picsum.photos/200/300?random=1",
    numberOfLockNow: 0,
    NumOfSchedule: 110,
    numOfLockByDailyLImit: 2,
    addictive: [
      { logo: "https://picsum.photos/200/370", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/270", appName: "youtube" },
    ],
    accountabilityPartner: {
      name: "Adetutu",
      email: "example@gmail.com",
    },
  },
  {
    id: 4,
    name: "Mr Obinna",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "09/01/1997",
    img: "https://picsum.photos/200/300?random=2",
    numberOfLockNow: 10,
    NumOfSchedule: 10,
    numOfLockByDailyLImit: 12,
    addictive: [
      { logo: "https://picsum.photos/200/260", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/270", appName: "youtube" },
      { logo: "https://picsum.photos/200/110", appName: "instagram" },
      { logo: "https://picsum.photos/200/130", appName: "twitter" },
    ],
    accountabilityPartner: {
      name: "Lucky",
      email: "example@gmail.com",
    },
  },
  {
    id: 5,
    name: "Mr Sammy",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "01/27/1998",
    img: "https://picsum.photos/200/300",
    numberOfLockNow: 50,
    NumOfSchedule: 1,
    numOfLockByDailyLImit: 21,
    addictive: [
      { logo: "https://picsum.photos/200/330", appName: "youtube" },
      { logo: "https://picsum.photos/200/600", appName: "instagram" },
      { logo: "https://picsum.photos/200/760", appName: "twitter" },
      { logo: "https://picsum.photos/200/980", appName: "google chrome" },
      { logo: "https://picsum.photos/200/321", appName: "opera news" },
    ],
    accountabilityPartner: {
      name: "Ifeanyi",
      email: "example@gmail.com",
    },
  },
  {
    id: 6,
    name: "Ehigiator",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "07/22/2003",
    img: "https://picsum.photos/200/300?random=1",
    numberOfLockNow: 0,
    NumOfSchedule: 110,
    numOfLockByDailyLImit: 2,
    addictive: [
      { logo: "https://picsum.photos/200/370", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/270", appName: "youtube" },
    ],
    accountabilityPartner: {
      name: "Adetutu",
      email: "example@gmail.com",
    },
  },
  {
    id: 7,
    name: "Mr Osayande",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "09/01/1997",
    img: "https://picsum.photos/200/300?random=2",
    numberOfLockNow: 10,
    NumOfSchedule: 10,
    numOfLockByDailyLImit: 12,
    addictive: [
      { logo: "https://picsum.photos/200/260", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/270", appName: "youtube" },
      { logo: "https://picsum.photos/200/110", appName: "instagram" },
      { logo: "https://picsum.photos/200/130", appName: "twitter" },
    ],
    accountabilityPartner: {
      name: "Lucky",
      email: "example@gmail.com",
    },
  },
  {
    id: 9,
    name: "Miss Ohis",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "07/22/2003",
    img: "https://picsum.photos/200/300?random=1",
    numberOfLockNow: 0,
    NumOfSchedule: 110,
    numOfLockByDailyLImit: 2,
    addictive: [
      { logo: "https://picsum.photos/200/370", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/270", appName: "youtube" },
    ],
    accountabilityPartner: {
      name: "Adetutu",
      email: "example@gmail.com",
    },
  },
  {
    id: 8,
    name: "Mrs Josephine",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "09/01/1997",
    img: "https://picsum.photos/200/300?random=2",
    numberOfLockNow: 10,
    NumOfSchedule: 10,
    numOfLockByDailyLImit: 12,
    addictive: [
      { logo: "https://picsum.photos/200/260", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/270", appName: "youtube" },
      { logo: "https://picsum.photos/200/110", appName: "instagram" },
      { logo: "https://picsum.photos/200/130", appName: "twitter" },
    ],
    accountabilityPartner: {
      name: "Lucky",
      email: "example@gmail.com",
    },
  },
  {
    id: 20,
    name: "Mrs Odinaka",
    number: 8055443614,
    email: "example@gmail.com",
    joined: "09/01/1997",
    img: "https://picsum.photos/200/300?random=2",
    numberOfLockNow: 10,
    NumOfSchedule: 10,
    numOfLockByDailyLImit: 12,
    addictive: [
      { logo: "https://picsum.photos/200/260", appName: "whatsApp" },
      { logo: "https://picsum.photos/200/270", appName: "youtube" },
      { logo: "https://picsum.photos/200/110", appName: "instagram" },
      { logo: "https://picsum.photos/200/130", appName: "twitter" },
    ],
    accountabilityPartner: {
      name: "Lucky",
      email: "example@gmail.com",
    },
  },
];

export function getUsers() {
  return Users;
}
